# Site settings
title: X.F.
description: "A blog about programing and life."
baseurl: "" # the subpath of your site
url: ""

# User settings
username: 大小棥
user_title: Lorem Ipsum - FrontEnd
email: 
twitter_username: 0xfann
github_username: ixfan
instagram_username: 0xfan
gplus_username:  
disqus_username: 

timezone: Asia/Chongqing

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
paginate_path: "/posts/page:num"

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: all posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: 这是中文
    url: https://github.com/victorvoid/asciilang
  - name: 中英文 English 混合
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 
gems: [jekyll-paginate]
exclude: ["src", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
